### ISSUE TITLE
Gem was built in 2011

### ISSUE THREAD

**Issue by murdoch** [bluemonk/ipaddress#42]
The latest version of this gem was released on May 16, 2011, but I can see that there have been several commits since then.

Should we be using the gem or would it be better to use the Github repo in our Gemfiles? Is there any reason why the latest commits have not been bundled into the official gem?

**Comment by schmurfy** [comment]
since this issue is still open I will comment here instead of creating a new one: can you please make a release now ?:)
I am still using my for fork because I was waiting for my pull request to be accepted, this was in 2011, the pull request was merged in 2014 but the latest released version do not include my changes (0.8.0) :(

I see 0.8.1 and 0.8.2 are mentioned in commits log but they were never release.

**Comment by bluemonk** [comment]
All right let's do this release :)
What do you guys prefer, 0.8.2 or straight to 1.0 even if a few things are still broken?

**Comment by msimkins** [comment]
If stuff is still broken - 0.8.2 or 0.9

**Comment by bluemonk** [comment]
Agreed. 0.8.2 released just now.

**Comment by schmurfy** [comment]
thanks !
